### ISSUE TITLE
Extension icon popup has wrong text

### ISSUE THREAD

**Issue by mwenell** [Webmie/My-Databank-App-and-Extension-2019#26]
PROBLEM

When you click svenska internetpaneen icon, it opens popup. The popup has text and below the text three buttons. The text has wrong text. It cannot ask to insert code below because there is no inpiut field.

"Skriv din personliga kod nedan. Du hittar din personliga kod i din inbjudan som borde finnas i din webbläsare eller som e-post."

SOLUTION

Different text here as it is in code views.

**Comment by Njugen** [comment]
Merely changing to "Använd din personliga kod för att godkänna projektet." makes the popup somehow vague. I used this text instead:

> För att kunna delta i Svenska internetpanelen behöver du en inbjudan och en personlig kod. Om du har en personlig kod, klicka på "Godkänn projektet" nedan för att använda det.

Which translates to:
"In order to participate in Svenska Internetpanelen, you need an invitation and a personal code. If you have a personal code, click 'Godkänn projektet' below to use it".

**Comment by Njugen** [comment]
New text:
"För att kunna delta i Svenska internetpanelen behöver du en inbjudan och en personlig kod. Om du har en personlig kod, klicka på "Godkänn projektet" nedan för att använda det."
